{
 "title": "TNC Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Packet RX Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(path)(ceil(increase(tnc_packet_rx[$__range])))\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Packet TX Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "ceil(increase(tnc_packet_tx[$__range]))\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Active Callsigns",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    {
     "expr": "topk(5, ceil(sum by (from_cs) (increase(tnc_packet_rx[$__range]))))",
     "legendFormat": "{{from_cs}}"
    }
   ]
  },
  {
   "title": "Max RX range of APRS position packets (km)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "targets": [
    { "expr": "tnc_max_range_recent / 1000", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "# Packets RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    { "expr": "tnc_packet_rx_recent", "legendFormat": "{{interval}}" }
   ]
  },
  {
   "title": "Packets RX/minute by APRS Path Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(path) (rate(tnc_packet_rx[$__interval]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Packets RX/minute by AX.25 Frame Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(ax25_frame_type) (rate(tnc_packet_rx[$__interval]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "# Packets TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "packets" } },
   "targets": [
    { "expr": "tnc_packet_tx_recent", "legendFormat": "{{interval}}" }
   ]
  },
  {
   "title": "Packets TX/minute by APRS Path Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tnc_packet_tx[$__interval]) * 60",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}